{{- if .Values.resourcequota -}}
{{- if .Values.resourcequota.enabled -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: qinsight-ui-compute-resources
spec:
  hard:

  {{- with .Values.resourcequota.hard }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
