{{- $postgrespassword := (randAlpha 64) | b64enc | quote  }}
{{- $dbiadminpassword := (randAlpha 64) | b64enc | quote  }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Release.Name ) }}
{{- if $secret }}
{{- $secretdata := $secret.data | default dict }}
{{- if hasKey $secretdata "postgres-password" }}
{{- $postgrespassword = index $secretdata "postgres-password" }}
{{- end }}
{{- if hasKey $secretdata "dundas-bi-admin-password" }}
{{- $dbiadminpassword = index $secretdata "dundas-bi-admin-password" }}
{{- end }}
{{- end -}}

{{- $createSecret := false }}
{{- if .Values.dundas.bi.appDb.express }}
{{- $createSecret = true }}
{{- end }}
{{- if not .Values.dundas.bi.appDb.useExistingSecretForAppDbConnString }}
{{- if not .Values.dundas.bi.appDb.express }} 
{{- $createSecret = true }}
{{- end }}
{{- end }}

{{- if not .Values.dundas.bi.appDb.useExistingSecretForWarehouseDbConnString }}
{{- if not .Values.dundas.bi.appDb.express }}
{{- if .Values.dundas.bi.appDb.warehouseDbConnString }}
{{- $createSecret = true }}
{{- end }}
{{- end }}
{{- end }}

{{- if or (.Values.dundas.bi.appDb.express) (.Values.dundas.bi.password.setAdminPassword) }} 
{{ if .Values.dundas.bi.password.generateRandomPassword }}
{{- $createSecret = true }}
{{ else }}
{{- $createSecret = true }}
{{ end }}
{{ end }} 
{{- if not .Values.dundas.bi.appDb.express }}
{{ if .Values.dundas.bi.appDb.appDbCreatorConnString }}
{{- $createSecret = true }}
{{ end }}
{{ if .Values.dundas.bi.appDb.whDbCreatorConnString }}
{{- $createSecret = true }}
{{ end }}
{{- end }}

{{- if $createSecret }}

apiVersion: v1
kind: Secret
metadata:
  name: qinsight-ui-secret
type: Opaque
data:
    {{- if .Values.dundas.bi.appDb.express }}
    postgres-password: {{ $postgrespassword }}
    {{- end }} 
    {{- if not .Values.dundas.bi.appDb.useExistingSecretForAppDbConnString }}
    {{- if not .Values.dundas.bi.appDb.express }} 
    DBI_CONNECTION_STRING: {{ .Values.dundas.bi.appDb.appDbConnString | b64enc }}
    {{- end }}
    {{- end }}
    
    {{- if not .Values.dundas.bi.appDb.useExistingSecretForWarehouseDbConnString }}
    {{- if not .Values.dundas.bi.appDb.express }}
    {{- if .Values.dundas.bi.appDb.warehouseDbConnString }}
    DBI_WAREHOUSE_CONNECTION_STRING: {{ .Values.dundas.bi.appDb.warehouseDbConnString | b64enc }}
    {{- end }}
    {{- end }}
    {{- end }}
    
    {{- if or (.Values.dundas.bi.appDb.express) (.Values.dundas.bi.password.setAdminPassword) }} 
      {{ if .Values.dundas.bi.password.generateRandomPassword }}
    dundas-bi-admin-password: {{ $dbiadminpassword }}
      {{ else if .Values.dundas.bi.password.useExistingSecretForAdminPassword }}
      # do nothing.
      {{ else }}
    dundas-bi-admin-password: "{{ .Values.dundas.bi.password.adminPassword | b64enc }}"
      {{ end }}
    {{ end }} 
    {{- if not .Values.dundas.bi.appDb.express }}
      {{ if .Values.dundas.bi.appDb.appDbCreatorConnString }}
    DBI_CREATOR_CONNECTION_STRING: {{ .Values.dundas.bi.appDb.appDbCreatorConnString | b64enc }}
      {{ end }}
      {{ if .Values.dundas.bi.appDb.whDbCreatorConnString }}
    DBI_WAREHOUSE_CREATOR_CONNECTION_STRING: {{ .Values.dundas.bi.appDb.whDbCreatorConnString | b64enc }}
      {{ end }}
    {{- end }}

{{- end }}


