{{- if .Values.dundas.bi.website.autoscaling.enabled }}
{{- if .Capabilities.APIVersions.Has "autoscaling/v2" -}}
apiVersion: autoscaling/v2
{{- else -}}
apiVersion: autoscaling/v2beta1
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: qinsight-ui-hpa
  labels:
    {{- include "dundas-bi.labels" . | nindent 4 }}
    app: dundas-bi-website
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.dundas.bi.website.kind }}
    name: {{ .Release.Name }}-dundas-bi-website
  minReplicas: {{ .Values.dundas.bi.website.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.dundas.bi.website.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.dundas.bi.website.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        {{- if .Capabilities.APIVersions.Has "autoscaling/v2" }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.dundas.bi.website.autoscaling.targetCPUUtilizationPercentage }}
        {{- else }}
        targetAverageUtilization: {{ .Values.dundas.bi.website.autoscaling.targetCPUUtilizationPercentage }}
        {{- end }}
  {{- end }}
  {{- if .Values.dundas.bi.website.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        {{- if .Capabilities.APIVersions.Has "autoscaling/v2" }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.dundas.bi.website.autoscaling.targetMemoryUtilizationPercentage }}
        {{- else }}
        targetAverageUtilization: {{ .Values.dundas.bi.website.autoscaling.targetMemoryUtilizationPercentage }}
        {{- end }}
  {{- end }}
{{- end }}
