{{- if .Values.dundas.bi.authbridge.enabled -}}
{{- if .Values.dundas.bi.authbridge.service.enabled -}}

kind: Service
apiVersion: v1
metadata:
  name: qinsight-ui-authbridge
  annotations:
  {{- with .Values.dundas.bi.authbridge.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.dundas.bi.cloud }}
  {{- if .Values.dundas.bi.cloud.google }}
  {{- if .Values.dundas.bi.cloud.google.enabled }} 
    cloud.google.com/neg: '{ "ingress" : true }' 
    cloud.google.com/backend-config: '{ "default": "{{ .Release.Name }}-dundas-bi-backendconfig" }'
  {{- end }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "dundas-bi.labels" . | nindent 4 }}
    app: dundas-bi-authbridge
spec:
  type: {{ .Values.dundas.bi.authbridge.service.type }}
  ports:
    - name: nginxhttp
      protocol: TCP
      port: {{ .Values.dundas.bi.authbridge.port }}
      targetPort: nginxhttp
  selector:
    {{- include "dundas-bi.selectorLabels" . | nindent 4 }}
    app: dundas-bi-authbridge
  sessionAffinity: {{ .Values.dundas.bi.authbridge.service.sessionAffinity }} 

{{- end }}
{{- end }}