{{- if .Values.dundas.bi.appDb.express -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: qinsight-ui-database
  labels:
    {{- include "dundas-bi.labels" . | nindent 4 }}
    app: dundas-bi-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dundas-bi-database
      {{- include "dundas-bi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: dundas-bi-database
        {{- include "dundas-bi.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: '{{ .Values.dundas.bi.appDb.expressimage }}' 
          ports:
            - name: postgresport
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: postgres-password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
          - name: pv-data-{{ .Release.Name }}
            mountPath: /var/lib/postgresql/data
          resources:
            {{- toYaml .Values.dundas.bi.appDb.expressresources | nindent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      volumes:
      - name: pv-data-{{ .Release.Name }}
        persistentVolumeClaim:
          claimName: dundas-bi-postgres-pv-claim-{{ .Release.Name }}
      restartPolicy: Always
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

