{{- if .Values.dundas.bi.cloud -}}
{{- if .Values.dundas.bi.cloud.google -}}
{{- if .Values.dundas.bi.cloud.google.enabled -}}
{{- if .Values.dundas.bi.cloud.google.backendconfig.enabled -}}
kind: BackendConfig
apiVersion: cloud.google.com/v1
metadata:
  name: qinsight-ui-backendconfig
spec:
  {{- with .Values.dundas.bi.cloud.google.backendconfig.spec }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}